### ISSUE TITLE
Only Chat Account?

### ISSUE THREAD

**Issue by smarteutech** [rndinfosecguy/vulture#1]
Hi! Its possible to track any number or it will work only for chat account with which we have talked before?
Thanks

**Comment by rndinfosecguy** [comment]
Hey! I tested it with two different accounts and it worked even when I never interacted with the other account.

**Comment by smarteutech** [comment]
Hi! Thats Good but I do not understood it properly. If you have never interacted with that user then how You have got that number in chat list? If I don't understood wrong, its provide information of number which is in chat list, Not ?
Thanks

**Comment by rndinfosecguy** [comment]
Yes you need the number of the person. You need to add it to the contact list of your phone and then open WhatsApp web, open a new chat in the webapp and select that number. Then you have a „clean“ chat window for that number and you can inject the JavaScript code. If you have a look at the readme you see that I put a screenshot there where I tested it against one of my test account I never interacted with.

**Comment by smarteutech** [comment]
Its working fine for people with which we have talked before, its not working for people with which we have never chat. its giving me error for contact number with We have not talked like this
`User not online - Privacy mode activated (TypeError: online[0] is undefined)`
Thanks

**Comment by smarteutech** [comment]
Actually I was using this for track numbers
https://github.com/LoranKloeze/WhatsAllApp
but its working now only for people with which we have talked only. If you have any knowledge regarding it, it will help me lot. 
Thanks

**Comment by rndinfosecguy** [comment]
Thanks for the hint. I will have a look at as soon as I am back from my trip!

**Comment by Junaid1111** [comment]
Have you find anything @rndinfosecguy  & @smarteutech ??
I am also looking into that but do not find anything...

**Comment by guyzahead** [comment]
hi can someone please detail the installation procedure? I have installed python3.8 and downloaded the zip

**Comment by ajay9022** [comment]
Does this also makes us appear online for the entire time that this your script will be running?
