### ISSUE TITLE
Not sending data

### ISSUE THREAD

**Issue by Division-x** [rndinfosecguy/vulture#2]
I'm trying the script and overall it works, but the failure is whenever a contact go from online to disconnected, it does not send the http request to the python server, however, if I do a test with a simulated environment in local (something like this)

```
<html>
	<head>
		<meta charset="UTF-8">
		<script>
			function changeStatus()
			{
			x=document.getElementsByClassName("_315-i");
			    for(var i = 0; i < x.length; i++){
			    	if (x[i].innerText == "online") {
			    		x[i].innerText=""; 
			    	} else {
			    		x[i].innerText="online";    
			    	}
			    }
			}
		</script>
	</head>
	<body>
		<span dir="auto" title="TEST USER" class="_19RFN">TEST USER</span>
		<br/>
		<span title="Test Content" class="_315-i">Test Content</span>
		<br/>
		<button type="button" onclick="changeStatus()">change status</button>
	</body>
</html>
```

it works perfectly and send the data to the localhost/cgi...

But on the real whatsapp it does nothing, any idea?

**Comment by rndinfosecguy** [comment]
Just returned to this project and tested. Unfortunately I cannot reproduce this issue. If you could add more details I could test your special case.

**Comment by rndinfosecguy** [comment]
Could not be reproduced
