### ISSUE TITLE
many phone number tracking

### ISSUE THREAD

**Issue by Alexvojander** [rndinfosecguy/vulture#4]
Hi, 
Learned your code and few another repositories 
it is possible to track many phone numbers at the same time? 
Even if they not in contact list. 
Thanks!v

**Comment by Junaid1111** [comment]
Hi...Can you please list other repositories?
Thanks...

**Comment by BEDIRHANSAMSA** [comment]
No, thanks

6 Ara 2019 Cum, saat 19:31 tarihinde Junaid Rana <notifications@github.com>
şunu yazdı:

**Comment by rndinfosecguy** [comment]
I am not aware of a method for multiple phone number tracking without having multiple sim cards and phones. If anybody has an idea you are welcome to share the idea :)
